declare module '@material-tailwind/react/Button'
declare module "@material-tailwind/react/Card"
declare module "@material-tailwind/react/Input"
declare module "@material-tailwind/react/Navbar";
declare module "@material-tailwind/react/NavbarContainer";
declare module "@material-tailwind/react/NavbarWrapper";
declare module "@material-tailwind/react/NavbarToggler";
declare module "@material-tailwind/react/NavbarCollapse";
declare module "@material-tailwind/react/Nav";
declare module "@material-tailwind/react/NavItem";